### ISSUE TITLE
Client report error

### ISSUE THREAD

**Issue by ReDBaroN1** [MGTDB/Exile_Block_Floor_Peeking#1]
Hey @MGTDB 

Just thought I'd pass on that sometimes this generates a client report error:
`10:39:40 Error in expression <ion in client_lowKneelAnimations;
};
if(client_inLowKneel) then
{
if(player weap>
10:39:40   Error position: <client_inLowKneel) then
{
if(player weap>
10:39:40   Error Undefined variable in expression: client_inlowkneel
10:39:40 File mpmissions\__CUR_MP.Altis\fixes\ExileClient_object_player_stats_update.sqf..., line 72`

Not sure of it's impact.

**Comment by MGTDB** [comment]
Sounds like https://github.com/MGTDB/Exile_Block_Floor_Peeking/blob/master/initPlayerLocal.sqf is misplaced in order in initPlayerLocal.sqf as that is where the global var client_inlowkneel is defined initially for the client

**Comment by ReDBaroN1** [comment]
only happens if you ninja your way in before fully initialised. closing, thanks @MGTDB
